#!/bin/bash
sudo pip3 install virtualenv
cd /home/ec2-user/app/sbrb-backend
virtualenv environment
source environment/bin/activate
sudo apt install postgresql
sudo pip3 install psycopg2-binary
sudo pip3 install psycopg2
sudo pip3 install -r requirements.txt