#!/bin/bash
sudo pkill -f /home/ubuntu/.local/bin/supervisord 

# Wait for the process to stop gracefully
sleep 60
cd /home/ec2-user/app
chmod +x scripts/start_server
chmod +w /tmp/supervisord.log
# sudo pip install supervisor
sudo /home/ubuntu/.local/bin/supervisord -c /home/ec2-user/app/supervisord.conf 


