#!/bin/bash
# sudo pkill -f /home/ubuntu/.local/bin/supervisord 
cd /home/ec2-user/app
chmod +x scripts/start_server
chmod +w /tmp/supervisord.log
# sudo pip install supervisor
sudo /home/ubuntu/.local/bin/supervisord -c /home/ec2-user/app/supervisord.conf 


