#!/bin/bash
# Stop the Supervisor-managed process (replace 'my-python-program' with the actual program name)
sudo supervisorctl stop main.py

sudo pkill -f /home/ubuntu/.local/bin/supervisord 

# Wait for the process to stop gracefully
sleep 60
cd /home/ec2-user/app
# Pull the latest code from the GitHub repository (assuming it's the 'main' branch)
# git pull origin main 
chmod +x scripts/start_server
chmod +w /tmp/supervisord.log
# sudo pip install supervisor
sudo /home/ubuntu/.local/bin/supervisord -c /home/ec2-user/app/supervisord.conf 


